apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Ureonspw/testimgnigx.git"
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
